name: doctor_appoinment_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.1
  onboarding_animation: ^0.0.3
  shared_preferences: ^2.2.3
  retrofit: ^4.4.1
  dio: ^5.7.0
  built_value: ^8.9.2
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  url_launcher: ^6.3.0
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.4
  flutter_datetime_picker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.2.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/icon/doctor/